#!/bin/sh

git diff --exit-code --name-only -- . ':(exclude)*.md'
EXIT_STATUS= echo $?
if [ $EXIT_STATUS -eq 1 ]; then
    COMMIT_MSG_FILE=$1
    SKIP_CI="[skip ci]"
    $SKIP_CI >> $COMMIT_MSG_FILE
fi
exit $EXIT_STATUS