#!/bin/bash

# from https://riptutorial.com/git/example/16164/pre-push

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

first_commit_branch=$(git log $protected_branch..HEAD --oneline --format="%H" | tail -1)
last_commit_branch=$(git rev-parse HEAD)

# check if any of the commits on the current branch are conventional
npm commitlint --from $first_commit_branch --to $last_commit_branch

if [ $protected_branch = $current_branch ] && [ exec < /dev/tty ]
then
    read -p "You're about to push master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0
    fi
    exit 1
else
    exit 0
fi
