#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

git diff --exit-code --name-only -- . ':(exclude)*.md'
if [ "$?" -eq 0 ]; then
    COMMIT_MSG_FILE=$1
    SKIP_CI="[skip ci]"
    echo "$SKIP_CI" >> $COMMIT_MSG_FILE
fi