#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "testing"

FILES=$(git diff --name-only -- . ':(exclude)*.md')
if [ -z "$FILES" ]; then
    COMMIT_MSG_FILE=$1
    SKIP_CI="[skip ci]"
    echo "$SKIP_CI" >> $COMMIT_MSG_FILE
fi